[Variables]
Main_FG =005394
Secondary_FG =FFFFFF
Main_BG =000000
Sidebar_And_Player_BG =000000
Cover_Overlay_And_Shadow =000000
Indicator_FG_And_Button_BG =005394
Pressing_FG = FF5C86
Slider_BG =000000
Sidebar_Indicator_And_Hover_Button_BG =005394
Scrollbar_FG_And_Selected_Row_BG =000000
Pressing_Button_FG =FFFFFF
Pressing_Button_BG =000000
Selected_Button =005394
Miscellaneous_BG =000000
Miscellaneous_Hover_BG =000000
Preserve_1 =FFFFFF
